# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

appraise 'rdkafka-0.12.x' do
  gem 'rdkafka', '~> 0.12.0'
end

appraise 'karafka-rdkafka-0.12.x' do
  gem 'karafka-rdkafka', '~> 0.12.0'
end
